import page from './cs2-keyboard-page.json';
import {canonicalKey, codeFromKey, displayKey} from './keys';
import {commandsOf} from './console';

export type KeyboardProfile = {
  /** Canonical CS2 key name -> console command, exactly like CS2's bind table. */
  binds: Readonly<Record<string, string>>;
  /** Lowercase alias name -> command text. */
  aliases: Readonly<Record<string, string>>;
  /** option_duck_method / option_speed_method: toggle instead of hold. */
  duckToggle: boolean;
  walkToggle: boolean;
  /** cl_debounce_zoom 0: holding Secondary Fire repeats it (CS2's "Repeat Enabled"). */
  zoomRepeat: boolean;
  /** zoom_sensitivity_ratio. */
  zoomSensitivity: number;
  /** Where the binds came from, shown in Settings. */
  source?: {label: string; at: string};
};

export type BindRow = {kind: 'bind'; id: string; label: string; bind: string; tooltip?: string};
export type EnumRow = {kind: 'enum'; label: string; convar?: string; bindkey?: string; values: {label: string; value: string}[]; tooltip?: string};
export type SliderRow = {kind: 'slider'; label: string; convar: string; min: number; max: number; precision: number};
export type PageRow = BindRow | EnumRow | SliderRow;
export type PageSection = {id: string; title: string; rows: PageRow[]};
/** CS2's Settings > Keyboard / Mouse page, generated by tools/import-keybinds.mjs. */
export const keyboardPage = page as unknown as {build: string; source: Record<string, string>; sections: PageSection[];
  defaults: Record<string, string>; analog: Record<string, string>};
export const bindRows = keyboardPage.sections.flatMap(section => section.rows).filter((row): row is BindRow => row.kind === 'bind');

const canonicalBinds = (binds: Record<string, string>) => Object.fromEntries(
  Object.entries(binds).flatMap(([key, command]) => {const name = canonicalKey(key); return name ? [[name, command]] : [];}));

/** CS2's stock bindings from user_keys_default.vcfg. */
export const cs2DefaultBinds: Readonly<Record<string, string>> = canonicalBinds(keyboardPage.defaults);

/**
 * SprayLab's defaults: CS2's, plus the trainer's long-standing extras. C crouches
 * because Ctrl+W closes browser tabs, 4 equips the Zeus and right Shift/Ctrl mirror the left keys.
 */
export const trainerDefaultBinds: Readonly<Record<string, string>> = {...cs2DefaultBinds, c: '+duck', '4': 'slot11', RSHIFT: '+sprint', RCTRL: '+duck'};

export const defaultKeyboard: KeyboardProfile = {binds: trainerDefaultBinds, aliases: {}, duckToggle: false, walkToggle: false, zoomRepeat: false, zoomSensitivity: 1};

/** Commands SprayLab acts on; other rows still round-trip through import and export. */
export const trainerCommands = new Set(['+forward', '+back', '+left', '+right', '+sprint', '+duck', '+jump', '+use', '+attack', '+attack2',
  '+reload', 'invprev', 'invnext', 'lastinv', 'drop', '+lookatweapon', 'slot1', 'slot2', 'slot3', 'slot11']);
/** Commands only AI Duel uses. */
export const duelOnlyCommands = new Set(['+use', 'drop']);

const limit = 4096;
export function sanitizeKeyboard(raw: unknown): KeyboardProfile {
  const value = (raw && typeof raw === 'object' ? raw : {}) as Partial<Record<keyof KeyboardProfile, unknown>>;
  const strings = (input: unknown, key: (name: string) => string | undefined) => {
    if (!input || typeof input !== 'object') return undefined;
    const entries = Object.entries(input as Record<string, unknown>).slice(0, 512).flatMap(([name, command]) => {
      const canonical = key(name);
      return canonical && typeof command === 'string' && command.length <= limit ? [[canonical, command]] : [];
    });
    return Object.fromEntries(entries) as Record<string, string>;
  };
  const source = value.source && typeof value.source === 'object' ? value.source as Record<string, unknown> : undefined;
  const zoom = typeof value.zoomSensitivity === 'number' && Number.isFinite(value.zoomSensitivity) ? Math.min(3, Math.max(.01, value.zoomSensitivity)) : 1;
  return {
    binds: strings(value.binds, canonicalKey) ?? trainerDefaultBinds,
    aliases: strings(value.aliases, name => /^[^\s;"]{1,64}$/.test(name) ? name.toLowerCase() : undefined) ?? {},
    duckToggle: value.duckToggle === true, walkToggle: value.walkToggle === true, zoomRepeat: value.zoomRepeat === true,
    zoomSensitivity: zoom,
    ...(source && typeof source.label === 'string' && typeof source.at === 'string'
      ? {source: {label: source.label.slice(0, 200), at: source.at.slice(0, 40)}} : {}),
  };
}

/**
 * Commands a key runs, with aliases expanded. `+name` binds also expand the
 * `+name` alias. Rebinding statements inside toggles are not followed.
 */
export function expandCommand(profile: Pick<KeyboardProfile, 'aliases'>, command: string, depth = 0, seen = new Set<string>()): string[] {
  if (depth > 8) return [];
  const result: string[] = [];
  for (const [name] of commandsOf(command)) {
    const lower = name.toLowerCase();
    const alias = profile.aliases[lower];
    if (alias !== undefined) {
      if (seen.has(lower)) continue;
      seen.add(lower); result.push(...expandCommand(profile, alias, depth + 1, seen));
    } else result.push(lower);
  }
  return result;
}

export type BoundKey = {key: string; direct: boolean};
/** Keys whose binding runs `command` directly or through an alias. */
export function keysFor(profile: Pick<KeyboardProfile, 'binds' | 'aliases'>, command: string): BoundKey[] {
  const target = command.toLowerCase();
  const keys: BoundKey[] = [];
  for (const [key, bound] of Object.entries(profile.binds)) {
    const commands = commandsOf(bound);
    const direct = commands.length === 1 && commands[0].join(' ').toLowerCase() === target;
    if (direct || expandCommand(profile, bound).includes(target)) keys.push({key, direct});
  }
  return keys.sort((a, b) => +b.direct - +a.direct || keyOrder(a.key) - keyOrder(b.key));
}

const order = new Map(Object.keys(cs2DefaultBinds).map((key, index) => [key, index]));
const keyOrder = (key: string) => order.get(key) ?? 1000 + key.charCodeAt(0);

/** Binds that do not belong to any row of CS2's page (custom aliases, cvars, say binds...). */
export function otherBinds(profile: Pick<KeyboardProfile, 'binds' | 'aliases'>) {
  const rowCommands = new Set(bindRows.map(row => row.bind.toLowerCase()));
  return Object.entries(profile.binds).filter(([, command]) => !expandCommand(profile, command).some(name => rowCommands.has(name)))
    .sort(([a], [b]) => keyOrder(a) - keyOrder(b));
}

/** First key bound to a command, for HUD hints such as "Inspect (F)". */
export const primaryKey = (profile: Pick<KeyboardProfile, 'binds' | 'aliases'>, command: string) => keysFor(profile, command)[0]?.key;
/** HUD hint for a command, such as "R" or "right click", or `fallback` when nothing is bound. */
export const keyHint = (profile: Pick<KeyboardProfile, 'binds' | 'aliases'>, command: string, fallback = 'unbound') => {
  const key = primaryKey(profile, command);
  return !key ? fallback : key === 'MOUSE1' ? 'left click' : key === 'MOUSE2' ? 'right click' : displayKey(key);
};
/** Key label for the trainer's slot buttons. Slot 4 is the Zeus, which CS2 also reaches through slot3. */
export function slotKey(profile: Pick<KeyboardProfile, 'binds' | 'aliases'>, slot: 1 | 2 | 3 | 4) {
  const key = primaryKey(profile, slot === 4 ? 'slot11' : `slot${slot}`) ?? (slot === 4 ? primaryKey(profile, 'slot3') : undefined);
  return key ? displayKey(key) : '-';
}

/**
 * KeyboardEvent codes to lock while fullscreen protection is on: every bound key
 * except Esc, Tab and the Windows keys, so Esc, Alt+Tab and the Start menu still work.
 */
export function protectedCodes(binds: Readonly<Record<string, string>>) {
  const free = new Set(['ESCAPE', 'TAB', 'LWIN', 'RWIN']);
  return [...new Set(Object.keys(binds).filter(key => !free.has(key)).flatMap(key => codeFromKey(key) ?? []))];
}

const modifiers = new Set(['CTRL', 'RCTRL', 'ALT', 'RALT', 'SHIFT', 'RSHIFT']);
const browserShortcuts = [
  ['CTRL', 'w', 'Ctrl+W may close this tab'], ['CTRL', 't', 'Ctrl+T may open a new tab'], ['CTRL', 'n', 'Ctrl+N may open a new window'],
  ['ALT', 'f', 'Alt+F may open the browser menu'], ['ALT', 'e', 'Alt+E may open the browser menu'],
  ['ALT', 'd', 'Alt+D may select the address bar'], ['ALT', 'LEFTARROW', 'Alt+Left may leave this page'],
] as const;
const verbs: Readonly<Record<string, string>> = {'+duck': 'crouch', '+sprint': 'walk', '+jump': 'jump', '+forward': 'move forward', '+back': 'move back', '+left': 'move left', '+right': 'move right'};

/**
 * Warning shown when fullscreen shortcut protection is unavailable: a held
 * trainer modifier plus another trainer key can form a browser shortcut.
 */
export function shortcutHint(profile: Pick<KeyboardProfile, 'binds' | 'aliases'>) {
  const trainer = (key: string) => expandCommand(profile, profile.binds[key] ?? '').find(name => trainerCommands.has(name));
  const risk = browserShortcuts.find(([modifier, key]) => trainer(modifier) && trainer(key));
  if (!risk) return undefined;
  const command = trainer(risk[0])!;
  const alternative = keysFor(profile, command).find(({key}) => !modifiers.has(key))?.key;
  return `${alternative ? `${displayKey(alternative)} to ${verbs[command] ?? 'use it'}. ` : ''}${risk[2]}.`;
}
